# Configure SonarCloud Automatic Analysis exclusions
sonar.exclusions=**/bin/**,**/obj/**,src/Leecharr.Frontend/node_modules/**,**/wwwroot/**,_output/**,_temp/**,src/Leecharr.Frontend/src/i18n/locales/**,**/locales/**,**/i18n/locales/**
sonar.cpd.exclusions=**/locales/**,**/locales/*,**/i18n/**,**/i18n/*,**/Migration/**,**/*Test*/**,**/Migrations/**,src/Leecharr.Frontend/src/i18n/locales/**
sonar.javascript.lcov.reportPaths=src/Leecharr.Frontend/coverage/lcov.info
