sonar.projectKey=dmzoneill_Leecharr
sonar.organization=dmzoneill
sonar.issue.ignore.multicriteria=e1,e2,e3,e4,e5,e6,e7,e8
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S2068
sonar.issue.ignore.multicriteria.e1.resourceKey=src/Leecharr.Frontend/src/i18n/**
sonar.issue.ignore.multicriteria.e2.ruleKey=typescript:S2068
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*Test*/**
sonar.issue.ignore.multicriteria.e3.ruleKey=roslyn.sonaranalyzer.security.cs:S3649
sonar.issue.ignore.multicriteria.e3.resourceKey=src/Leecharr.Api.V1/System/SystemDatabaseController.cs
sonar.issue.ignore.multicriteria.e4.ruleKey=roslyn.sonaranalyzer.security.cs:S6776
sonar.issue.ignore.multicriteria.e4.resourceKey=src/Leecharr.Api.V1/System/SystemController.cs
sonar.issue.ignore.multicriteria.e5.ruleKey=roslyn.sonaranalyzer.security.cs:S6549
sonar.issue.ignore.multicriteria.e5.resourceKey=src/Leecharr.Api.V1/**
sonar.issue.ignore.multicriteria.e6.ruleKey=roslyn.sonaranalyzer.security.cs:S5144
sonar.issue.ignore.multicriteria.e6.resourceKey=src/Leecharr.Api.V1/**
sonar.issue.ignore.multicriteria.e7.ruleKey=csharpsquid:S5332
sonar.issue.ignore.multicriteria.e7.resourceKey=src/NzbDrone.Host/Bootstrap.cs
sonar.issue.ignore.multicriteria.e8.ruleKey=typescript:S5332
sonar.issue.ignore.multicriteria.e8.resourceKey=src/Leecharr.Frontend/**
