sonar.projectKey=dmzoneill_Leecharr
sonar.organization=dmzoneill
sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S2068
sonar.issue.ignore.multicriteria.e1.resourceKey=src/Leecharr.Frontend/src/i18n/locales/**
sonar.issue.ignore.multicriteria.e2.ruleKey=typescript:S2068
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*Test*/**
