<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NzbDrone.Common\Leecharr.Common.csproj" />
    <ProjectReference Include="..\NzbDrone.Core\Leecharr.Core.csproj" />
    <ProjectReference Include="..\Leecharr.Http\Leecharr.Http.csproj" />
    <ProjectReference Include="..\Leecharr.Api.V1\Leecharr.Api.V1.csproj" />
    <ProjectReference Include="..\NzbDrone.SignalR\Leecharr.SignalR.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NSubstitute" Version="6.2.0" />
    <PackageReference Include="FluentAssertions" Version="8.1.1" />
  </ItemGroup>
</Project>
